# Generated by Django 4.1.1 on 2022-10-01 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_car'),
    ]

    operations = [
        migrations.DeleteModel(
            name='car',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='name',
        ),
        migrations.AddField(
            model_name='tweet',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
