# Generated by Django 4.1.1 on 2022-10-01 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_delete_car_remove_tweet_name_tweet_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='date',
            field=models.TextField(default='0000-01-01'),
        ),
        migrations.AddField(
            model_name='tweet',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
