# Generated by Django 4.1.1 on 2022-10-01 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_tweet_date_tweet_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='date',
            field=models.DateTimeField(default='0000-01-01 00:00:00'),
        ),
    ]
