# Generated by Django 4.1.1 on 2022-10-01 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_alter_tweet_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet_hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=150)),
                ('user_id', models.IntegerField(default=0)),
                ('date', models.DateTimeField(default='0000-01-01 00:00:00')),
                ('text', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Tweet_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('user_id', models.IntegerField(default=0)),
                ('date', models.DateTimeField(default='0000-01-01 00:00:00')),
                ('text', models.TextField(default='')),
            ],
        ),
        migrations.DeleteModel(
            name='Tweet',
        ),
    ]
